[package]
name = "rust_learning"
version = "0.1.0"
edition = "2024"

[dependencies]
num = "0.4.3"
rand = "0.9.1"
rayon = "1.10.0"
tokio = { version = "1.46.1", features = ["full"] }
uuid = { version = "1.17.0", features = ["v4"] }
